### ISSUE TITLE
LaTeX Error - Failed to execute 'transaction' on 'IDBDatabase'

### ISSUE THREAD

**Issue by darshanpatel44** [shelwinsunga/jules#14]
LaTeX Error
Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

![image](https://github.com/user-attachments/assets/2357e253-2b96-4d24-bae1-036abb70b60b)

**Comment by shelwinsunga** [comment]
Hey - is this still an issue? If so, could you give me the latex causing this?

**Comment by darshanpatel44** [comment]
Oh its working now! 
Thank You!
